spring:
  application:
    name: productms
# This configuration tells producer prioritizes reliability over latency. High durability producer
  kafka:
    producer:
      bootstrap-server: localhost:9092,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      acks: all #leader waits all in-sync replicas before acknowledging (higher latency, high durability) -> production-grade
      properties:
        enable:
          idempotence: true # avoids duplicate messages even if network glitch happens (safe tries)
        max:
          in:
            flight:
              requests:
                per:
                  connection: 5 #how many unacknowledged requests can exist simultaneously per connection
        delivery:
          timeout:
            ms: 120000 #total amount Kafka Producer will try to deliver a message before failing permanently
        linger:
          ms: 0 #sends immediately, no batching delay (Latency vs Throughput)
        request:
          timeout:
            ms: 30000 #broker has 30 s to respond to a single request
#      retries: 10 #how many times producer will retry sending a message if it fails
#      properties:
#        retry:
#          backoff:
#            ms: 1000 #how long producer waits between retry attempts



