spring:
  application:
    name: productms

  kafka:
    producer:
      bootstrap-server: localhost:9092,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      acks: all
      properties:
        enable:
          idempotence: true
        max:
          in:
            flight:
              requests:
                per:
                  connection: 5
        delivery:
          timeout:
            ms: 120000 #total amount Kafka will try to deliver a message before failing permanently
        linger:
          ms: 0 #sends immediately, no batching delay
        request:
          timeout:
            ms: 30000
#      retries: 10 #how many times producer will retry sending a message if it fails
#      properties:
#        retry:
#          backoff:
#            ms: 1000 #how long producer waits between retry attempts



